apiVersion: v1
kind: Service
metadata:
  name: test-demo
  labels:
    name: test-demo
    app: test-demo
spec:
  type: LoadBalancer
  selector:
    name: test-demo
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo
  labels:
    name: test-demo
    app: test-demo
spec:
  selector:
    matchLabels:
      app: test-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: test-demo
      labels:
        name: test-demo
        app: test-demo
    spec:
      containers:
        - name: test-demo
          image: 050455579260.dkr.ecr.ap-south-1.amazonaws.com/test-demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-demo
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 4
