apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
    app: hello-world-service
spec:
  type: LoadBalancer
  selector:
    name: hello-world-service
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-service
  labels:
    name: hello-world-service
    app: hello-world-service
spec:
  selector:
    matchLabels:
      app: hello-world-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: hello-world-service
      labels:
        name: hello-world-service
        app: hello-world-service
    spec:
      containers:
        - name: hello-world01
          image: 050455579260.dkr.ecr.ap-south-1.amazonaws.com/test-demo:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-service
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hello-world-service
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 4
